# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Chorus BDD
tagline:          'BDD testing for distributed systems'
description:      'BDD testing for distributed systems'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Chorus BDD'
  url:            https://github.com/Chorus-bdd/

paginate:         2

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Chorus-bdd/

gems: [jekyll_github_sample]
