package org.chorusbdd.chorus.core.interpreter.parser;

/**
* User: nick
* Date: 27/01/14
* Time: 18:07
*/
enum ParserState {
    START,
    READING_FEATURE_DESCRIPTION,
    READING_SCENARIO_STEPS,
    READING_SCENARIO_BACKGROUND_STEPS,
    READING_SCENARIO_OUTLINE_STEPS,
    READING_EXAMPLES_TABLE,
    READING_STEP_MACRO,
    READING_USES,
    READING_TAGS,
    READING_FEATURE_START, READING_FEATURE_END, READING_CONFIGURATIONS
}
